version: "3.8"

services:
  # Database container
  db:
    image: postgres:14
    container_name: local-postgres-db
    environment:
      POSTGRES_USER: "avnadmin"
      POSTGRES_PASSWORD: "AVNS_dHiqX_MZoCTikAcb7qd"
      POSTGRES_DB: "defaultdb"
    ports:
      - "5432:5432"
    # If you want to persist data locally between container restarts,
    # you can uncomment and adjust the volume mapping below:
    # volumes:
    #   - ./postgres_data:/var/lib/postgresql/data

  # Spring Boot application container
  spring-boot-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: spring-boot-app
    ports:
      - "8080:8080"
    environment:
      # Point the Spring Boot app to the 'db' service name (Docker DNS)
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/defaultdb?sslmode=disable"
      SPRING_DATASOURCE_USERNAME: "avnadmin"
      SPRING_DATASOURCE_PASSWORD: "AVNS_dHiqX_MZoCTikAcb7qd"
    depends_on:
      - db
